name = "roll-doradogame-ca"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=roll-doradogame.ca"
HMAC_KEY = "5b92bd60bb2a5317bf71c1759044314c57e526ede3bfeeed19d0052336b84ad2"
COOKIE_NAME = "sl6"
PLAY_PATH = "explore"
BUTTON_ID = "pb2e25d638150b9be0bdc5e5372829564"
GATE_SALT = "0f0a18a1c5d4eb07"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "tf5i"
CTA_SELECTOR = ".play-button"
